scripts[lab-record-gen]: fix make not skipping steps due to wrong rule

diff --git a/Scripts/Lab_Record_Generator/Makefile b/Scripts/Lab_Record_Generator/Makefile
--- a/Scripts/Lab_Record_Generator/Makefile
+++ b/Scripts/Lab_Record_Generator/Makefile
@@ -19,18 +19,17 @@ DEPENDENCIES_SCRIPT = ./check-dependencies-pandoc.sh
 PANDOC_METADATA = metadata.yaml
 PANDOC_HEADER_INCLUDE = deeplists.tex
 PDF_VIEWER = zathura
+LIBREOFFICE_TOOL = libreoffice
 
 # === Targets ===
 all: $(PDF_FILE)
 
 # Main PDF generation rule that selects the appropriate method
-$(PDF_FILE): PDF-FROM-$(INTERMEDIATE_FORMAT)
-	@echo "--- Generated PDF file: $(PDF_FILE) ---"
-
-# PDF generation from Markdown
-PDF-FROM-MARKDOWN: $(MARKDOWN_FILE) $(TEMPLATE_FILE) $(PANDOC_METADATA) $(PANDOC_HEADER_INCLUDE)
-	@echo "--- Generating PDF from Markdown ---"
-	@pandoc \
+$(PDF_FILE): $($(INTERMEDIATE_FORMAT:=_FILE))
+	@echo "--- Generating PDF file: $(PDF_FILE) ---"
+	@if [ "$(INTERMEDIATE_FORMAT)" = "MARKDOWN" ]; then \
+		echo "Using pandoc for conversion from $(INTERMEDIATE_FORMAT)"; \
+		pandoc \
 		--output=$(PDF_FILE) \
 		--standalone \
 		--include-in-header=$(PANDOC_HEADER_INCLUDE) \
@@ -39,38 +38,26 @@ PDF-FROM-MARKDOWN: $(MARKDOWN_FILE) $(TEMPLATE_FILE) $(PANDOC_METADATA) $(PANDOC
 		--from=markdown \
 		--to=pdf \
 		$(MARKDOWN_FILE) || { \
-		echo "ERROR: Failed to generate PDF file from Markdown."; \
-		echo "Run make checkdepends to ensure all dependencies are met."; \
-		exit 1; \
-	}
-
-# PDF generation from DOCX
-PDF-FROM-DOCX: $(DOCX_FILE)
-	@echo "--- Generating PDF from DOCX ---"
-	libreoffice \
-		--convert-to pdf \
-		$(DOCX_FILE) || { \
-		echo "ERROR: Failed to generate PDF file from DOCX."; \
-		echo "Run make checkdepends to ensure all dependencies are met."; \
-		exit 1; \
-	}
-
-# PDF generation from ODT
-PDF-FROM-ODT: $(ODT_FILE)
-	@echo "--- Generating PDF from ODT ---"
-	libreoffice \
-		--convert-to pdf \
-		$(ODT_FILE) || { \
-		echo "ERROR: Failed to generate PDF file from ODT."; \
-		echo "Run make checkdepends to ensure all dependencies are met."; \
-		exit 1; \
-	}
+			echo "ERROR: Failed to generate PDF file."; \
+			echo "Run make checkdepends to ensure all dependencies are met."; \
+			exit 1; \
+		}; \
+	else \
+		echo "Using $(LIBREOFFICE_TOOL) for conversion from $(INTERMEDIATE_FORMAT)"; \
+		$(LIBREOFFICE_TOOL) --convert-to pdf $($(INTERMEDIATE_FORMAT:=_FILE)) || { \
+			echo "ERROR: Failed to generate PDF file."; \
+			echo "Run make checkdepends to ensure all dependencies are met."; \
+			exit 1; \
+		}; \
+	fi
+	@echo "--- Generated PDF file: $(PDF_FILE) ---"
 
 $(DOCX_FILE): $(MARKDOWN_FILE)
 	@echo "--- Generating DOCX file: $(DOCX_FILE) ---"
 	pandoc \
 		--output=$(DOCX_FILE) \
 		--metadata-file=$(PANDOC_METADATA) \
+		--standalone \
 		--from=markdown \
 		--to=docx \
 		$(MARKDOWN_FILE)
@@ -80,6 +67,7 @@ $(ODT_FILE): $(MARKDOWN_FILE)
 	pandoc \
 		--output=$(ODT_FILE) \
 		--metadata-file=$(PANDOC_METADATA) \
+		--standalone \
 		--from=markdown \
 		--to=odt \
 		$(MARKDOWN_FILE)
@@ -88,13 +76,13 @@ $(MARKDOWN_FILE): $(GENERATION_SCRIPT)
 	@echo "--- Generating Markdown file $(MARKDOWN_FILE) using files from $(FILES) ---"
 	MAIN_CODE_FILENAME="$(MAIN_CODE_FILENAME)" CODE_EXTENSIONS="$(CODE_EXTENSIONS)" $(GENERATION_SCRIPT) $(MARKDOWN_FILE) $(FILES)
 
-# Explicitly run the Markdown generation step.
-markdown: $(MARKDOWN_FILE)
-	@echo "--- Markdown file ensured up-to-date ---"
-
 # Explicitly run the PDF generation step.
 pdf: $(PDF_FILE)
 	@echo "--- PDF file ensured up-to-date ---"
+
+# Explicitly run the Markdown generation step.
+markdown: $(MARKDOWN_FILE)
+	@echo "--- Markdown file ensured up-to-date ---"
 
 # Explicitly run the docx generation step.
 docx: $(DOCX_FILE)
@@ -119,4 +107,4 @@ checkdepends:
 	$(DEPENDENCIES_SCRIPT)
 
 # Declare targets that do not correspond to actual files.
-.PHONY: all pdf markdown docx odt show clean checkdepends PDF-FROM-MARKDOWN pdf-from-DOCX pdf-from-ODT
+.PHONY: all pdf markdown docx odt show clean checkdepends
